url: "https://mrpeppapig.github.io"
baseurl: "/www.mrpeppapig.com"

collections:
  authors:
    output: true
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-youtube

environment: production

sass:
   sass_dir: assets/css
   
